repo: https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz
ver: 3.0.16
tag_prefix: openssl-
tag_dot2ul: false
cb_tool: custom
options: 'no-tests'
options_unix: no-comp no-async no-shared
options_embed: no-dso no-engine no-hw
options_msw: no-comp enable-md4
options_wasm: no-asm no-threads no-ssl3 no-dtls no-engine no-dso linux-x32 -static
options_wasm64: no-asm no-threads no-ssl3 no-dtls no-engine no-dso linux-generic64 -static
